project_id = "aeilvaampnacbcrpkkyi"

[functions.whatsapp-qrcode]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.booking-agent]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-manual-message]
verify_jwt = false
